# Generated by Django 6.0 on 2026-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={"ordering": ["name"], "verbose_name_plural": "categories"},
        ),
        migrations.AddField(
            model_name="event",
            name="city",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
